#!/usr/bin/ash

TPM2_LUKS_CONFIG_FILE="/etc/tpm2luks.conf"
TPM2_LUKS_SECRET="crypto_keyfile.bin"

message() {
  echo "$@" >&2
  return 0
}

run_hook() {

    # load variables from conf file
    . "$TPM2_LUKS_CONFIG_FILE" || {
      message "Failed to read the configuration file '$TPM2_LUKS_CONFIG_FILE'"
      return 1
    }

    # sanity check
    if [ -z "$TPM2_LUKS_DEV" ]; then
      message "Please check TPM2_LUKS_DEV in $TPM2_LUKS_CONFIG_FILE"
      return 1
    fi

    # add tpm modules
    modprobe -a -q tpm_crb

    tpm2_unseal -c 0x81000000 -p pcr:sha1:0,2,4,7 -o $TPM2_LUKS_SECRET

    cryptsetup --key-file $TPM2_LUKS_SECRET luksOpen $TPM2_LUKS_DEV $TPM2_LUKS_NAME
    _decrypted=$?
    if [ "$_decrypted" -eq 0 ]; then
      echo "TPM - Boot Partition decryption was successful"
      shred -u $TPM2_LUKS_SECRET
    else
      echo "TPM - Boot Partition decryption was failed"
      echo "TPM - Software Integrity Check is failed"
      echo "!!!!!!!!! EVIL MAID ATTACK !!!!!!!!!"
      echo "!!!!!!!!! ABORT BOOT PROCESS !!!!!!!"
      shred -u $TPM2_LUKS_SECRET
      sleep 30
      return 1
    fi
}
