#!/usr/bin/ash

run_hook() {
    modprobe -a -q tpm_crb >/dev/null 2>&1
    tpm2_unseal -c 0x81000000 -p pcr:sha1:0,2,4,7 -o crypto_keyfile.bin
    cryptsetup --key-file crypto_keyfile.bin luksOpen /dev/sda2 luks_boot
    shred -u crypto_keyfile.bin
    echo "Boot partition is decrypted."
}

# vim: set ft=sh ts=4 sw=4 et:
