#!/bin/bash

build() {
    local mod

    add_module "tpm_crb"
    add_module "tpm_tis"
    add_module "tpm_tis_core"
    add_module "tpm"
    add_module "rng_core"

    add_binary "tpm2_unseal"
    add_binary "/usr/lib/libtss2-tcti-device.so"
    add_binary "/usr/lib/libtss2-tcti-device.so.0"

    add_runscript
}

help() {
    cat <<HELPEOF
This hook allows decrypting a LUKS partition using TPM.
HELPEOF
}
